data_folder: data

unzip_dataset:
  input_file: benchmark.zip
  output_folder: benchmark_unzip

split_dataset:
  seed: 1337
  test_ratio: 0.2
  train_ratio: 0.6
  val_ratio: 0.2
  output_folder: benchmark_split